Pagination and grammar fixes for 500.html file
CompanionshipCare/companionship-care pull request #156
Opened 2022-11-14 09:04 UTC by Shaikha1212

resolves https://github.com/CompanionshipCare/companionship-care/issues/15

2022-11-14 09:08 UTC, Shaikha1212 commented
Just wanted to mention that when running the manage.py test line in the terminal all tests pass

2022-11-15 11:03 UTC, brylie requested changes

2022-11-15 11:03 UTC, brylie commented on project/circles/views.py
> +            print(activities_page)
Let's remove these print statements.

2022-11-15 11:06 UTC, brylie requested changes

2022-11-15 11:06 UTC, brylie commented on project/circles/templates/circles/circle_detail.html
> +              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
Remember the i18n tag here.
```suggestion
              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">
                  {% translate "Previous" %}
              </a>
```

2022-11-15 11:06 UTC, brylie commented on project/circles/templates/circles/circle_detail.html
> +              <a class="page-link" href="?page={{ activity_page.next_page_number }}">Next</a>
Add i18n:
```suggestion
              <a class="page-link" href="?page={{ activity_page.next_page_number }}">
                  {% translate "Next" %}
              </a>
```

2022-11-15 11:06 UTC, brylie commented on project/circles/templates/circles/circle_detail.html
> +              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
i18n:
```suggestion
              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">
                  {% translate "Next" %}
              </a>
```

2022-11-15 15:06 UTC, closed without merging